[project]
name = "aventura-rd-backend"
version = "0.1.0"
description = "AventuraRD API REST"
authors = [
    {name = "Spencer",email = "Spencerrrrd@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = "^3.10"
dependencies = [
    "fastapi (>=0.136.3,<0.137.0)",
    "uvicorn (>=0.48.0,<0.49.0)",
    "sqlalchemy (>=2.0.50,<3.0.0)",
    "pymysql (>=1.2.0,<2.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "pydantic-settings (>=2.14.1,<3.0.0)",
    "cryptography (>=48.0.0,<49.0.0)",
    "bcrypt (>=5.0.0,<6.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
